import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Exact design tokens from the HTML files
        background:                  "#121413",
        surface:                     "#121413",
        "surface-dim":               "#121413",
        "surface-bright":            "#383a38",
        "surface-container-lowest":  "#0d0f0e",
        "surface-container-low":     "#1a1c1b",
        "surface-container":         "#1e201f",
        "surface-container-high":    "#282a29",
        "surface-container-highest": "#333534",
        "surface-variant":           "#333534",
        "surface-tint":              "#9ed900",
        "on-surface":                "#e2e3e0",
        "on-surface-variant":        "#c2caad",
        "on-background":             "#e2e3e0",
        "primary":                   "#ffffff",
        "primary-fixed":             "#b4f700",
        "primary-fixed-dim":         "#9ed900",
        "primary-container":         "#b4f700",
        "on-primary":                "#243600",
        "on-primary-fixed":          "#141f00",
        "on-primary-fixed-variant":  "#374e00",
        "on-primary-container":      "#4f6e00",
        "inverse-primary":           "#4a6800",
        "secondary":                 "#ffb59a",
        "secondary-container":       "#ff5e07",
        "secondary-fixed":           "#ffdbce",
        "secondary-fixed-dim":       "#ffb59a",
        "on-secondary":              "#5a1b00",
        "on-secondary-fixed":        "#370e00",
        "on-secondary-fixed-variant":"#802a00",
        "on-secondary-container":    "#531900",
        "tertiary":                  "#ffffff",
        "tertiary-fixed":            "#7df4ff",
        "tertiary-fixed-dim":        "#00dbe9",
        "tertiary-container":        "#7df4ff",
        "on-tertiary":               "#00363a",
        "on-tertiary-fixed":         "#002022",
        "on-tertiary-fixed-variant": "#004f54",
        "on-tertiary-container":     "#006f77",
        "outline":                   "#8c9479",
        "outline-variant":           "#424933",
        "error":                     "#ffb4ab",
        "error-container":           "#93000a",
        "on-error":                  "#690005",
        "on-error-container":        "#ffdad6",
        "inverse-surface":           "#e2e3e0",
        "inverse-on-surface":        "#2f3130",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        gutter: "1rem",
        margin: "1rem",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        sans:    ["Geist", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "label-caps":          ["11px", { lineHeight: "14px", fontWeight: "700" }],
        "label-sm":            ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md":             ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-bold":           ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-lg":             ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md":         ["20px", { lineHeight: "26px", fontWeight: "600" }],
        "headline-lg-mobile":  ["24px", { lineHeight: "30px", fontWeight: "700" }],
        "headline-lg":         ["32px", { lineHeight: "38px", fontWeight: "700" }],
        "display-hero-mobile": ["36px", { lineHeight: "42px", fontWeight: "700" }],
        "metric-numeral":      ["44px", { lineHeight: "48px", fontWeight: "700" }],
        "display-hero":        ["56px", { lineHeight: "64px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
